[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python backend/main.py"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
PORT = "8000"

