services:
  - type: web
    name: celestialguide-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: OPENCAGE_API_KEY
        sync: false
      - key: OPENWEATHERMAP_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
    disk:
      name: celestial-data
      mountPath: /opt/render/project/src/backend/data
      sizeGB: 10
